knp_snappy:
    pdf:
        enabled: true
        binary: 'C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe'

#    image:
#        enabled:    true
#        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
#        options:    []
