<?php

/**
 * Wojewodztwa i Powiaty.
 */

namespace App\DataFixtures;

use App\Entity\Powiat;
use App\Entity\Wojewodztwo;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

/**
 * WojewodztwaPowiaty class.
 */
class WojewodztwaPowiaty extends Fixture
{
    /**
     * Loads the data.
     *
     * @param ObjectManager $manager ObjectManager
     */
    public function load(ObjectManager $manager): void
    {
        $data = [
            'Dolnośląskie' => [
                'Wrocław',
                'Jelenia Góra',
                'Legnica',
                'Wałbrzych',
                'Bolesławiecki',
                'Dzierżoniowski',
                'Głogowski',
                'Górowski',
                'Jaworski',
                'Jeleniogórski',
                'Kamiennogórski',
                'Kłodzki',
                'Legnicki',
                'Lubański',
                'Lubiński',
                'Lwówecki',
                'Milicki',
                'Oleśnicki',
                'Oławski',
                'Polkowicki',
                'Strzeliński',
                'Średzki',
                'Świdnicki',
                'Trzebnicki',
                'Wałbrzyski',
                'Wołowski',
                'Wrocławski',
                'Ząbkowicki',
                'Zgorzelecki',
                'Złotoryjski',
            ],
            'Kujawsko-Pomorskie' => [
                'Bydgoszcz',
                'Toruń',
                'Włocławek',
                'Grudziądz',
                'Aleksandrowski',
                'Brodnicki',
                'Bydgoski',
                'Chełmiński',
                'Golubsko-Dobrzyński',
                'Grudziądzki',
                'Inowrocławski',
                'Lipnowski',
                'Mogileński',
                'Nakielski',
                'Radziejowski',
                'Rypiński',
                'Sępoleński',
                'Świecki',
                'Toruński',
                'Tucholski',
                'Wąbrzeski',
                'Włocławski',
                'Żniński',
            ],
            'Lubelskie' => [
                'Lublin',
                'Biała Podlaska',
                'Chełm',
                'Zamość',
                'Bialski',
                'Biłgorajski',
                'Chełmski',
                'Hrubieszowski',
                'Janowski',
                'Krasnostawski',
                'Kraśnicki',
                'Lubartowski',
                'Lubelski',
                'Łęczyński',
                'Łukowski',
                'Opolski',
                'Parczewski',
                'Puławski',
                'Radzyński',
                'Rycki',
                'Świdnicki',
                'Tomaszowski',
                'Włodawski',
                'Zamojski',
            ],
            'Lubuskie' => [
                'Gorzów Wielkopolski',
                'Zielona Góra',
                'Gorzowski',
                'Krośnieński',
                'Międzyrzecki',
                'Nowosolski',
                'Słubicki',
                'Strzelecko-Drezdenecki',
                'Sulęciński',
                'Świebodziński',
                'Wschowski',
                'Zielonogórski',
                'Żagański',
                'Żarski',
            ],
            'Łódzkie' => [
                'Łódź',
                'Piotrków Trybunalski',
                'Skierniewice',
                'Bełchatowski',
                'Brzeziński',
                'Kutnowski',
                'Łaski',
                'Łęczycki',
                'Łowicki',
                'Łódzki Wschodni',
                'Opoczyński',
                'Pabianicki',
                'Pajęczański',
                'Piotrkowski',
                'Poddębicki',
                'Radomszczański',
                'Rawski',
                'Sieradzki',
                'Skierniewicki',
                'Tomaszowski',
                'Wieluński',
                'Wieruszowski',
                'Zduńskowolski',
                'Zgierski',
            ],
            'Małopolskie' => [
                'Kraków',
                'Nowy Sącz',
                'Tarnów',
                'Bocheński',
                'Brzeski',
                'Chrzanowski',
                'Dąbrowski',
                'Gorlicki',
                'Krakowski',
                'Limanowski',
                'Miechowski',
                'Myślenicki',
                'Nowosądecki',
                'Nowotarski',
                'Olkuski',
                'Oświęcimski',
                'Proszowicki',
                'Suski',
                'Tarnowski',
                'Tatrzański',
                'Wadowicki',
                'Wielicki',
            ],
            'Mazowieckie' => [
                'Warszawa',
                'Ostrołęka',
                'Płock',
                'Radom',
                'Siedlce',
                'Białobrzeski',
                'Ciechanowski',
                'Garwoliński',
                'Gostyniński',
                'Grodziski',
                'Grójecki',
                'Kozienicki',
                'Legionowski',
                'Lipski',
                'Łosicki',
                'Makowski',
                'Miński',
                'Mławski',
                'Nowodworski',
                'Ostrołęcki',
                'Ostrowski',
                'Otwocki',
                'Piaseczyński',
                'Płocki',
                'Płoński',
                'Pruszkowski',
                'Przasnyski',
                'Przysuski',
                'Pułtuski',
                'Radomski',
                'Siedlecki',
                'Sierpecki',
                'Sochaczewski',
                'Sokołowski',
                'Szydłowiecki',
                'Warszawski-Zachodni',
                'Węgrowski',
                'Wołomiński',
                'Wyszkowski',
                'Zwoleński',
                'Żuromiński',
                'Żyrardowski',
            ],
            'Opolskie' => [
                'Opole',
                'Brzeski',
                'Głubczycki',
                'Kędzierzyńsko-Kozielski',
                'Kluczborski',
                'Krapkowicki',
                'Namysłowski',
                'Nyski',
                'Oleski',
                'Opolski',
                'Prudnicki',
                'Strzelecki',
            ],
            'Podkarpackie' => [
                'Rzeszów',
                'Krosno',
                'Przemyśl',
                'Tarnobrzeg',
                'Bieszczadzki',
                'Brzozowski',
                'Dębicki',
                'Jarosławski',
                'Jasielski',
                'Kolbuszowski',
                'Krośnieński',
                'Leski',
                'Leżajski',
                'Lubaczowski',
                'Łańcucki',
                'Mielecki',
                'Niżański',
                'Przemyski',
                'Przeworski',
                'Ropczycko-Sędziszowski',
                'Rzeszowski',
                'Sanocki',
                'Stalowowolski',
                'Strzyżowski',
                'Tarnobrzeski',
            ],
            'Podlaskie' => [
                'Białystok',
                'Łomża',
                'Suwałki',
                'Augustowski',
                'Białostocki',
                'Bielski',
                'Grajewski',
                'Hajnowski',
                'Kolneński',
                'Łomżyński',
                'Moniecki',
                'Sejneński',
                'Siemiatycki',
                'Sokólski',
                'Suwalski',
                'Wysokomazowiecki',
                'Zambrowski',
            ],
            'Pomorskie' => [
                'Gdańsk',
                'Gdynia',
                'Słupsk',
                'Sopot',
                'Bytowski',
                'Chojnicki',
                'Człuchowski',
                'Kartuski',
                'Kościerski',
                'Kwidzyński',
                'Lęborski',
                'Malborski',
                'Nowodworski',
                'Gdański',
                'Pucki',
                'Słupski',
                'Starogardzki',
                'Sztumski',
                'Tczewski',
                'Wejherowski',
            ],
            'Śląskie' => [
                'Katowice',
                'Bielsko-Biała',
                'Bytom',
                'Chorzów',
                'Częstochowa',
                'Dąbrowa Górnicza',
                'Gliwice',
                'Jastrzębie-Zdrój',
                'Jaworzno',
                'Mysłowice',
                'Piekary Śląskie',
                'Ruda Śląska',
                'Rybnik',
                'Siemianowice Śląskie',
                'Sosnowiec',
                'Świętochłowice',
                'Tychy',
                'Zabrze',
                'Żory',
                'Będziński',
                'Bielski',
                'Bieruńsko-Lędziński',
                'Cieszyński',
                'Częstochowski',
                'Gliwicki',
                'Kłobucki',
                'Lubliniecki',
                'Mikołowski',
                'Myszkowski',
                'Pszczyński',
                'Raciborski',
                'Rybnicki',
                'Tarnogórski',
                'Wodzisławski',
                'Zawierciański',
                'Żywiecki',
            ],
            'Świętokrzyskie' => [
                'Kielce',
                'Buski',
                'Jędrzejowski',
                'Kazimierski',
                'Kielecki',
                'Konecki',
                'Opatowski',
                'Ostrowiecki',
                'Pińczowski',
                'Sandomierski',
                'Skarżyski',
                'Starachowicki',
                'Staszowski',
                'Włoszczowski',
            ],
            'Warmińsko-Mazurskie' => [
                'Olsztyn',
                'Elbląg',
                'Bartoszycki',
                'Braniewski',
                'Działdowski',
                'Elbląski',
                'Ełcki',
                'Giżycki',
                'Gołdapski',
                'Iławski',
                'Kętrzyński',
                'Lidzbarski',
                'Mrągowski',
                'Nidzicki',
                'Nowomiejski',
                'Olecki',
                'Olsztyński',
                'Ostródzki',
                'Piski',
                'Szczycieński',
                'Węgorzewski',
            ],
            'Wielkopolskie' => [
                'Poznań',
                'Kalisz',
                'Konin',
                'Leszno',
                'Chodzieski',
                'Czarnkowsko-Trzcianecki',
                'Gnieźnieński',
                'Gostyński',
                'Grodziski',
                'Jarociński',
                'Kaliski',
                'Kępiński',
                'Kolski',
                'Koniński',
                'Kościański',
                'Krotoszyński',
                'Leszczyński',
                'Międzychodzki',
                'Nowotomyski',
                'Obornicki',
                'Ostrowski',
                'Ostrzeszowski',
                'Pilski',
                'Pleszewski',
                'Poznański',
                'Rawicki',
                'Słupecki',
                'Szamotulski',
                'Średzki',
                'Śremski',
                'Turecki',
                'Wągrowiecki',
                'Wolsztyński',
                'Wrzesiński',
                'Złotowski',
            ],
            'Zachodniopomorskie' => [
                'Szczecin',
                'Koszalin',
                'Świnoujście',
                'Białogardzki',
                'Choszczeński',
                'Drawski',
                'Goleniowski',
                'Gryficki',
                'Gryfiński',
                'Kamieński',
                'Kołobrzeski',
                'Koszaliński',
                'Łobeski',
                'Myśliborski',
                'Policki',
                'Pyrzycki',
                'Sławieński',
                'Stargardzki',
                'Szczecinecki',
                'Świdwiński',
                'Wałecki',
            ],
        ];

        foreach ($data as $wojewodztwoName => $powiaty) {
            $wojewodztwo = new Wojewodztwo();
            $wojewodztwo->setName($wojewodztwoName);
            $manager->persist($wojewodztwo);

            foreach ($powiaty as $powiatName) {
                $powiat = new Powiat();
                $powiat->setName($powiatName);
                $powiat->setWojewodztwo($wojewodztwo);
                $manager->persist($powiat);
            }
        }

        $manager->flush();
    }
}
